const categories = {
  online: [
    { id: 'website' },
    { id: 'logo' },
    { id: 'translation' },
    { id: 'flyer' },
    { id: 'consulting' },
    { id: 'architecture' },
    { id: 'dataentry' },
    { id: 'photovideo' },
    { id: 'sns' },
    { id: 'onlinesupport' },
    { id: 'education' },
    { id: 'fundraising' },
    { id: 'longtermrole' },
    { id: 'explainer' },
    { id: 'other-online' },
  ],
  local: [
    { id: 'cleaning' },
    { id: 'teaching' },
    { id: 'food_distribution' },
    { id: 'elderly_support' },
    { id: 'animal_care' },
    { id: 'environment' },
    { id: 'community_events' },
    { id: 'childcare' },
    { id: 'manual_labor' },
    { id: 'administrative' },
    { id: 'other-local' },
  ],
  event: [
    { id: 'fundraising_event' },
    { id: 'awareness_campaign' },
    { id: 'workshop' },
    { id: 'seminar_conference' },
    { id: 'charity_walk' },
    { id: 'networking' },
    { id: 'arts_and_crafts' },
    { id: 'food_fair' },
    { id: 'other-event' },
  ],
};

export default categories;
