import {
  HiCode,
  HiPencil,
  HiTranslate,
  HiDocumentText,
  HiLightBulb,
  HiDatabase,
  HiCamera,
  HiShare,
  HiSupport,
  HiAcademicCap,
  HiHeart,
  HiPlay,
  HiQuestionMarkCircle,
  HiSparkles,
  HiBookOpen,
  HiTruck,
  HiUserGroup,
  HiUsers,
  HiClipboardList,
  HiGift,
  HiPresentationChartLine,
  HiUserCircle,
  HiShoppingBag,
} from 'react-icons/hi';
import { HiClock } from 'react-icons/hi2';
import { FaPaw, FaLeaf, FaChild, FaWrench, FaPaintBrush } from 'react-icons/fa';
import { IoMegaphone } from 'react-icons/io5';

// Category icon mapping - shared across all components
export const categoryIcons = {
  website: HiCode,
  logo: HiPencil,
  translation: HiTranslate,
  flyer: HiDocumentText,
  consulting: HiLightBulb,
  architecture: HiSparkles,
  dataentry: HiDatabase,
  photovideo: HiCamera,
  sns: HiShare,
  onlinesupport: HiSupport,
  education: HiAcademicCap,
  fundraising: HiHeart,
  longtermrole: HiClock,
  explainer: HiPlay,
  other: HiQuestionMarkCircle,
  cleaning: HiSparkles,
  teaching: HiBookOpen,
  food_distribution: HiTruck,
  elderly_support: HiUserGroup,
  animal_care: FaPaw,
  environment: FaLeaf,
  community_events: HiUsers,
  childcare: FaChild,
  manual_labor: FaWrench,
  administrative: HiClipboardList,
  fundraising_event: HiGift,
  awareness_campaign: IoMegaphone,
  workshop: HiPresentationChartLine,
  seminar_conference: HiUserCircle,
  charity_walk: HiUsers,
  networking: HiUserGroup,
  arts_and_crafts: FaPaintBrush,
  food_fair: HiShoppingBag,
};

