/**
 * Leaderboard continent mapping.
 * Maps country codes (ISO 3166-1 alpha-2) to continents:
 * americas, africa, asia, europe, oceania.
 */

/** @type {Record<string, string>} Country code -> continent id */
const countryToContinent = {
  // Americas (North + South combined)
  "US": "americas",
  "CA": "americas",
  "MX": "americas",
  "GT": "americas",
  "BZ": "americas",
  "SV": "americas",
  "HN": "americas",
  "NI": "americas",
  "CR": "americas",
  "PA": "americas",
  "CU": "americas",
  "JM": "americas",
  "HT": "americas",
  "DO": "americas",
  "BS": "americas",
  "BB": "americas",
  "TT": "americas",
  "GD": "americas",
  "LC": "americas",
  "VC": "americas",
  "AG": "americas",
  "KN": "americas",
  "DM": "americas",
  "BR": "americas",
  "AR": "americas",
  "CO": "americas",
  "PE": "americas",
  "VE": "americas",
  "CL": "americas",
  "EC": "americas",
  "BO": "americas",
  "PY": "americas",
  "UY": "americas",
  "GY": "americas",
  "SR": "americas",
  "GF": "americas",
  "FK": "americas",
  // Europe
  "GB": "europe",
  "FR": "europe",
  "DE": "europe",
  "IT": "europe",
  "ES": "europe",
  "PL": "europe",
  "NL": "europe",
  "BE": "europe",
  "GR": "europe",
  "PT": "europe",
  "CZ": "europe",
  "RO": "europe",
  "HU": "europe",
  "SE": "europe",
  "AT": "europe",
  "CH": "europe",
  "BG": "europe",
  "DK": "europe",
  "FI": "europe",
  "SK": "europe",
  "IE": "europe",
  "HR": "europe",
  "NO": "europe",
  "RS": "europe",
  "SI": "europe",
  "LT": "europe",
  "LV": "europe",
  "EE": "europe",
  "LU": "europe",
  "CY": "europe",
  "MT": "europe",
  "IS": "europe",
  "AL": "europe",
  "MK": "europe",
  "BA": "europe",
  "ME": "europe",
  "RU": "europe",
  "UA": "europe",
  "BY": "europe",
  "MD": "europe",
  "GE": "europe",
  "AM": "europe",
  "AZ": "europe",
  // Asia
  "CN": "asia",
  "IN": "asia",
  "ID": "asia",
  "PK": "asia",
  "BD": "asia",
  "JP": "asia",
  "PH": "asia",
  "VN": "asia",
  "TH": "asia",
  "MY": "asia",
  "MM": "asia",
  "KR": "asia",
  "KH": "asia",
  "LA": "asia",
  "SG": "asia",
  "TW": "asia",
  "HK": "asia",
  "MN": "asia",
  "NP": "asia",
  "LK": "asia",
  "AF": "asia",
  "KZ": "asia",
  "UZ": "asia",
  "SA": "asia",
  "IR": "asia",
  "IQ": "asia",
  "AE": "asia",
  "IL": "asia",
  "JO": "asia",
  "LB": "asia",
  "KW": "asia",
  "OM": "asia",
  "QA": "asia",
  "BH": "asia",
  "YE": "asia",
  "TR": "asia",
  "TM": "asia",
  "TJ": "asia",
  "KG": "asia",
  // Africa
  "NG": "africa",
  "ET": "africa",
  "EG": "africa",
  "CD": "africa",
  "TZ": "africa",
  "ZA": "africa",
  "KE": "africa",
  "UG": "africa",
  "SD": "africa",
  "DZ": "africa",
  "MA": "africa",
  "AO": "africa",
  "GH": "africa",
  "MZ": "africa",
  "MG": "africa",
  "CM": "africa",
  "CI": "africa",
  "NE": "africa",
  "BF": "africa",
  "ML": "africa",
  "MW": "africa",
  "ZM": "africa",
  "SN": "africa",
  "TD": "africa",
  "ZW": "africa",
  "GN": "africa",
  "RW": "africa",
  "BJ": "africa",
  "TN": "africa",
  "BI": "africa",
  "SS": "africa",
  "SO": "africa",
  "TG": "africa",
  "ER": "africa",
  "SL": "africa",
  "LY": "africa",
  "CG": "africa",
  "LR": "africa",
  "CF": "africa",
  "MR": "africa",
  "GM": "africa",
  "GW": "africa",
  "DJ": "africa",
  "BW": "africa",
  "LS": "africa",
  "GQ": "africa",
  "GA": "africa",
  "MU": "africa",
  "EH": "africa",
  "SC": "africa",
  "CV": "africa",
  "KM": "africa",
  "ST": "africa",
  "RE": "africa",
  "YT": "africa",
  "SH": "africa",
  // Oceania
  "AU": "oceania",
  "NZ": "oceania",
  "PG": "oceania",
  "FJ": "oceania",
  "SB": "oceania",
  "NC": "oceania",
  "PF": "oceania",
  "VU": "oceania",
  "WS": "oceania",
  "KI": "oceania",
  "FM": "oceania",
  "TO": "oceania",
  "MH": "oceania",
  "PW": "oceania",
  "TV": "oceania",
  "NR": "oceania",
  "CK": "oceania",
  "NU": "oceania",
  "AS": "oceania",
  "GU": "oceania",
  "MP": "oceania",
};

/** Continent id -> display label */
export const CONTINENT_LABELS = {
  americas: "Americas",
  africa: "Africa",
  asia: "Asia",
  europe: "Europe",
  oceania: "Oceania",
};

/**
 * Get continent for a country code.
 * @param {string} countryCode - ISO 3166-1 alpha-2 country code
 * @return {{ id: string, label: string } | null}
 */
export function getContinent(countryCode) {
  if (!countryCode) return null;
  const id = countryToContinent[countryCode.toUpperCase()];
  if (!id) return null;
  return {id, label: CONTINENT_LABELS[id] ?? id};
}
