/**
 * Continent Mapping Utility
 * Maps country codes (ISO 3166-1 alpha-2) to continent badge IDs
 */

const countryToContinent = {
  // North America
  'US': 'north-america',
  'CA': 'north-america',
  'MX': 'north-america',
  'GT': 'north-america',
  'BZ': 'north-america',
  'SV': 'north-america',
  'HN': 'north-america',
  'NI': 'north-america',
  'CR': 'north-america',
  'PA': 'north-america',
  'CU': 'north-america',
  'JM': 'north-america',
  'HT': 'north-america',
  'DO': 'north-america',
  'BS': 'north-america',
  'BB': 'north-america',
  'TT': 'north-america',
  'GD': 'north-america',
  'LC': 'north-america',
  'VC': 'north-america',
  'AG': 'north-america',
  'KN': 'north-america',
  'DM': 'north-america',
  
  // South America
  'BR': 'south-america',
  'AR': 'south-america',
  'CO': 'south-america',
  'PE': 'south-america',
  'VE': 'south-america',
  'CL': 'south-america',
  'EC': 'south-america',
  'BO': 'south-america',
  'PY': 'south-america',
  'UY': 'south-america',
  'GY': 'south-america',
  'SR': 'south-america',
  'GF': 'south-america',
  'FK': 'south-america',
  
  // Europe
  'GB': 'europe',
  'FR': 'europe',
  'DE': 'europe',
  'IT': 'europe',
  'ES': 'europe',
  'PL': 'europe',
  'NL': 'europe',
  'BE': 'europe',
  'GR': 'europe',
  'PT': 'europe',
  'CZ': 'europe',
  'RO': 'europe',
  'HU': 'europe',
  'SE': 'europe',
  'AT': 'europe',
  'CH': 'europe',
  'BG': 'europe',
  'DK': 'europe',
  'FI': 'europe',
  'SK': 'europe',
  'IE': 'europe',
  'HR': 'europe',
  'NO': 'europe',
  'RS': 'europe',
  'SI': 'europe',
  'LT': 'europe',
  'LV': 'europe',
  'EE': 'europe',
  'LU': 'europe',
  'CY': 'europe',
  'MT': 'europe',
  'IS': 'europe',
  'AL': 'europe',
  'MK': 'europe',
  'BA': 'europe',
  'ME': 'europe',
  'RU': 'europe',
  'UA': 'europe',
  'BY': 'europe',
  'MD': 'europe',
  'GE': 'europe',
  'AM': 'europe',
  'AZ': 'europe',
  
  // Asia
  'CN': 'asia',
  'IN': 'asia',
  'ID': 'asia',
  'PK': 'asia',
  'BD': 'asia',
  'JP': 'asia',
  'PH': 'asia',
  'VN': 'asia',
  'TH': 'asia',
  'MY': 'asia',
  'MM': 'asia',
  'KR': 'asia',
  'KH': 'asia',
  'LA': 'asia',
  'SG': 'asia',
  'TW': 'asia',
  'HK': 'asia',
  'MN': 'asia',
  'NP': 'asia',
  'LK': 'asia',
  'AF': 'asia',
  'KZ': 'asia',
  'UZ': 'asia',
  'SA': 'asia',
  'IR': 'asia',
  'IQ': 'asia',
  'AE': 'asia',
  'IL': 'asia',
  'JO': 'asia',
  'LB': 'asia',
  'KW': 'asia',
  'OM': 'asia',
  'QA': 'asia',
  'BH': 'asia',
  'YE': 'asia',
  'TR': 'asia',
  'TM': 'asia',
  'TJ': 'asia',
  'KG': 'asia',
  
  // Africa
  'NG': 'africa',
  'ET': 'africa',
  'EG': 'africa',
  'CD': 'africa',
  'TZ': 'africa',
  'ZA': 'africa',
  'KE': 'africa',
  'UG': 'africa',
  'SD': 'africa',
  'DZ': 'africa',
  'MA': 'africa',
  'AO': 'africa',
  'GH': 'africa',
  'MZ': 'africa',
  'MG': 'africa',
  'CM': 'africa',
  'CI': 'africa',
  'NE': 'africa',
  'BF': 'africa',
  'ML': 'africa',
  'MW': 'africa',
  'ZM': 'africa',
  'SN': 'africa',
  'TD': 'africa',
  'ZW': 'africa',
  'GN': 'africa',
  'RW': 'africa',
  'BJ': 'africa',
  'TN': 'africa',
  'BI': 'africa',
  'SS': 'africa',
  'SO': 'africa',
  'TG': 'africa',
  'ER': 'africa',
  'SL': 'africa',
  'LY': 'africa',
  'CG': 'africa',
  'LR': 'africa',
  'CF': 'africa',
  'MR': 'africa',
  'GM': 'africa',
  'GW': 'africa',
  'DJ': 'africa',
  'BW': 'africa',
  'LS': 'africa',
  'GQ': 'africa',
  'GA': 'africa',
  'MU': 'africa',
  'EH': 'africa',
  'SC': 'africa',
  'CV': 'africa',
  'KM': 'africa',
  'ST': 'africa',
  'RE': 'africa',
  'YT': 'africa',
  'SH': 'africa',
  
  // Oceania
  'AU': 'oceania',
  'NZ': 'oceania',
  'PG': 'oceania',
  'FJ': 'oceania',
  'SB': 'oceania',
  'NC': 'oceania',
  'PF': 'oceania',
  'VU': 'oceania',
  'WS': 'oceania',
  'KI': 'oceania',
  'FM': 'oceania',
  'TO': 'oceania',
  'MH': 'oceania',
  'PW': 'oceania',
  'TV': 'oceania',
  'NR': 'oceania',
  'CK': 'oceania',
  'NU': 'oceania',
  'AS': 'oceania',
  'GU': 'oceania',
  'MP': 'oceania',
};

/**
 * Get continent badge ID from country code
 * @param {string} countryCode - ISO 3166-1 alpha-2 country code
 * @returns {string|null} Continent badge ID or null if not found
 */
export function getContinentFromCountry(countryCode) {
  if (!countryCode) {
    return null;
  }
  
  const upperCode = countryCode.toUpperCase();
  return countryToContinent[upperCode] || null;
}

/**
 * Get all countries for a continent
 * @param {string} continentId - Continent badge ID
 * @returns {Array<string>} Array of country codes
 */
export function getCountriesForContinent(continentId) {
  return Object.keys(countryToContinent).filter(
    code => countryToContinent[code] === continentId
  );
}

