/* eslint-disable max-len */
import {onCall} from "firebase-functions/v2/https";
import {db} from "../init.js";
import ExcelJS from "exceljs";
import {EXPORT_TRANSLATIONS} from "./exportTranslations.js";

/**
 * Convert value to Date.
 * @param {*} value - Timestamp, Date, or date-like.
 * @return {Date|null}
 */
function toDate(value) {
  if (!value) return null;
  if (value?.toDate) return value.toDate();
  if (value?.seconds != null) return new Date(value.seconds * 1000);
  if (value instanceof Date) return value;
  return new Date(value);
}

/**
 * Combine date with HH:mm time string.
 * @param {*} date - Date-like.
 * @param {string} timeStr - HH:mm.
 * @return {Date|null}
 */
function combineDateAndTime(date, timeStr) {
  if (!date || !timeStr) return null;
  const d = toDate(date);
  if (!d) return null;
  const [hours, minutes] = String(timeStr).split(":").map((n) => Number(n));
  const out = new Date(d);
  const h = Number.isFinite(hours) ? hours : 0;
  const m = Number.isFinite(minutes) ? minutes : 0;
  out.setHours(h, m, 0, 0);
  return out;
}

/**
 * Get activity duration in hours.
 * @param {Object} activity - Activity doc.
 * @return {number|null}
 */
function getActivityDurationHours(activity) {
  if (!activity) return null;
  const hasTime = activity.start_time || activity.end_time;
  const startDate = toDate(activity.start_date);
  if (!startDate || !hasTime) return null;
  const start = combineDateAndTime(
      activity.start_date,
      activity.start_time || "00:00");
  const endDateRaw = activity.end_date || activity.start_date;
  const end = combineDateAndTime(
      endDateRaw,
      activity.end_time || activity.start_time || "00:00");
  if (!start || !end) return null;
  const ms = end.getTime() - start.getTime();
  if (!(ms > 0)) return null;
  return ms / (1000 * 60 * 60);
}

/**
 * Format parameter value for display (fixes unit duplication).
 * Never show "count"; never append "hours" if label already contains it.
 * @param {string} label - Parameter label.
 * @param {number} value - Numeric value.
 * @param {string} unit - Unit string.
 * @return {string}
 */
function formatParamValue(label, value, unit) {
  const u = (unit || "").trim().toLowerCase();
  const labelLower = (label || "").toLowerCase();
  if (u === "count") return `${label}: ${value}`;
  if (u === "hours" && labelLower.includes("hours")) return `${label}: ${value}`;
  return u ? `${label}: ${value} ${unit.trim()}` : `${label}: ${value}`;
}

/**
 * Check if activity qualifies for auto-generated organizational capacity.
 * Returns the virtual param or null.
 * Uses duration (from start/end times) first; falls back to impact_results.total_hours
 * when duration is missing (e.g. online activities storing hours differently).
 * @param {Object} activity - Activity doc.
 * @param {number} volunteerCount - Validated volunteer count.
 * @param {number|null} durHours - Duration in hours from getActivityDurationHours.
 * @param {number} totalHours - impact_results.total_hours (fallback when duration missing).
 * @param {Object} categoryLabels - Map of category id -> label.
 * @return {{label: string, value: number, unit: string, measurementType: string, sdg: *, isAutoGenerated: boolean}|null}
 */
function getAutoGeneratedOrgCapacity(activity, volunteerCount, durHours, totalHours, categoryLabels) {
  const isOnline = activity.type === "online";
  const impactParams = activity.impact_parameters || [];
  const hasNoParameters = impactParams.length === 0;

  let hoursAvailable = 0;
  if (durHours != null && durHours > 0) {
    hoursAvailable = (volunteerCount || 0) * durHours;
  } else {
    hoursAvailable = Number(totalHours) || 0;
  }
  const hasHours = hoursAvailable > 0;

  if (!isOnline || !hasNoParameters || !hasHours) return null;

  const hours = parseFloat(Number(hoursAvailable).toFixed(1));
  const category = activity.category;
  const label = categoryLabels[category] || category || "Other";

  return {
    label,
    value: hours,
    unit: "hours",
    measurementType: "organizational_capacity",
    sdg: activity.sdg,
    isAutoGenerated: true,
  };
}

/**
 * Get the date to use for filtering/display when start_date may be missing
 * (e.g. some online activities). Prefer start_date, then updated_at, then closedAt.
 * @param {Object} activity - Activity doc.
 * @return {Date|null}
 */
function getActivityDateForFilter(activity) {
  const start = toDate(activity.start_date);
  if (start) return start;
  const lastUpdated = toDate(activity.updated_at);
  if (lastUpdated) return lastUpdated;
  return toDate(activity.impact_results?.closed_at);
}

/**
 * Extract SDG number from various formats.
 * @param {string|number} sdg - SDG value.
 * @return {string}
 */
function getSDGNumber(sdg) {
  if (typeof sdg === "number") return String(sdg);
  if (typeof sdg === "string") {
    if (sdg.startsWith("Goal-")) {
      return sdg.replace("Goal-", "").replace(/^0+/, "") || "1";
    }
    return sdg;
  }
  return sdg;
}

/**
 * Callable: Export impact report as Excel for NPO.
 */
export const exportImpactReport = onCall(
    {
      invoker: "public",
      memory: "1GiB",
      timeoutSeconds: 120,
    },
    async (request) => {
      if (!request.auth) {
        throw new Error("Unauthorized");
      }

      const orgId = request.auth.token?.npo_id;
      if (!orgId) {
        throw new Error("Forbidden: NPO access required");
      }

      const {startDate, endDate, locale = "en"} = request.data || {};
      if (!startDate || !endDate || typeof startDate !== "string" || typeof endDate !== "string") {
        throw new Error("startDate and endDate are required (ISO strings)");
      }

      const t = EXPORT_TRANSLATIONS[locale] || EXPORT_TRANSLATIONS.en;
      const start = new Date(startDate);
      const end = new Date(endDate);
      if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) {
        throw new Error("Invalid date format");
      }
      if (start > end) {
        throw new Error("startDate must be before endDate");
      }

      // Query activities: orgId, status=Closed
      const activitiesSnap = await db
          .collection("activities")
          .where("organization_id", "==", orgId)
          .where("status", "==", "Closed")
          .get();

      const allActivities = activitiesSnap.docs.map((doc) => ({id: doc.id, ...doc.data()}));

      // Filter by date within range (start_date, else updated_at, else closedAt)
      const activities = allActivities.filter((a) => {
        const d = getActivityDateForFilter(a);
        if (!d) return false;
        const t = d.getTime();
        return t >= start.getTime() && t <= end.getTime();
      });

      if (activities.length === 0) {
        return {success: false, error: "zeroActivities"};
      }

      // Fetch org
      const orgDoc = await db.collection("organizations").doc(orgId).get();
      const org = orgDoc.exists ? orgDoc.data() : {};
      const orgName = org.name || org.display_name || orgId;
      const orgNameStr = typeof orgName === "string" ? orgName : (orgName?.en || orgName?.fr || orgId);

      // Fetch global + custom parameters for NPO
      const [globalSnap, customSnap] = await Promise.all([
        db.collection("impact_parameters").where("scope", "==", "global").where("is_active", "==", true).get(),
        db.collection("organizations").doc(orgId).collection("customParameters").get(),
      ]);

      const paramById = new Map();
      globalSnap.docs.forEach((d) => paramById.set(d.id, {id: d.id, ...d.data(), scope: "global"}));
      customSnap.docs.forEach((d) => {
        const data = d.data();
        if (data.is_active !== false) paramById.set(d.id, {id: d.id, ...data, scope: "npo"});
      });

      // Collect unique volunteers, volunteer count per activity, SDG data
      const uniqueVolunteers = new Set();
      const volunteerCountByActivity = {};
      const activitySdgData = {};
      let totalHours = 0;
      let activitiesWithoutDuration = 0;

      for (const act of activities) {
        if (act.type === "event") continue;
        const ir = act.impact_results || {};
        const hrs = ir.total_hours ?? 0;
        totalHours += Number(hrs) || 0;
        const dur = getActivityDurationHours(act);
        const hasTotalHours = Number(hrs) > 0;
        const hasDuration = dur != null && dur > 0;
        if (!hasTotalHours && !hasDuration) activitiesWithoutDuration++;

        const partSnap = await db.collection("activities").doc(act.id).collection("participations").get();
        const valSnap = await db.collection("activities").doc(act.id).collection("validations").get();
        const validatedIds = new Set(
            valSnap.docs.map((d) => d.data().user_id).filter(Boolean),
        );
        const volunteerIds = new Set();
        partSnap.docs.forEach((d) => {
          const uid = d.id;
          const data = d.data();
          if (validatedIds.has(uid) || data.status === "validated") {
            uniqueVolunteers.add(uid);
            volunteerIds.add(uid);
          }
        });
        volunteerCountByActivity[act.id] = volunteerIds.size;

        const sdgVal = act.sdg;
        if (sdgVal != null) {
          const n = Number(getSDGNumber(sdgVal));
          if (!activitySdgData[n]) activitySdgData[n] = {activities: new Set(), hours: 0, volunteers: new Set()};
          activitySdgData[n].activities.add(act.id);
          activitySdgData[n].hours += Number(hrs) || 0;
          volunteerIds.forEach((id) => activitySdgData[n].volunteers.add(id));
        }
      }

      // Aggregate parameters by measurement type
      const paramSums = {};
      const paramMeta = {};
      const unclassified = [];

      for (const act of activities) {
        const params = act.impact_results?.parameters || {};
        const impactParams = act.impact_parameters || [];
        for (const [paramId, value] of Object.entries(params)) {
          const num = Number(value) || 0;
          if (num <= 0) continue;
          paramSums[paramId] = (paramSums[paramId] || 0) + num;
          const def = paramById.get(paramId);
          const actParam = impactParams.find((p) => (p.parameter_id || p.id) === paramId);
          const mt = actParam?.measurement_type || def?.measurement_type;
          paramMeta[paramId] = {
            label: def?.label || actParam?.label || paramId,
            unit: def?.unit || actParam?.unit || "",
            measurement_type: mt || null,
          };
        }
      }

      for (const [paramId, meta] of Object.entries(paramMeta)) {
        if (!meta.measurement_type && (paramSums[paramId] || 0) > 0) {
          unclassified.push({...meta, paramId, total: paramSums[paramId]});
        }
      }

      // Auto-generated organizational capacity for online activities with no params
      const autoGenByCategory = {};
      let hasAutoGenParams = false;
      for (const act of activities) {
        const durHours = getActivityDurationHours(act);
        const volunteerCount = volunteerCountByActivity[act.id] ?? 0;
        const totalHrs = (act.impact_results?.total_hours ?? 0);
        const auto = getAutoGeneratedOrgCapacity(act, volunteerCount, durHours, totalHrs, t.categoryLabels);
        if (auto) {
          hasAutoGenParams = true;
          autoGenByCategory[auto.label] = (autoGenByCategory[auto.label] || 0) + auto.value;
        }
      }

      // Activity-level SDGs (unique)
      const activitySdgs = new Set();
      activities.forEach((a) => {
        const sdg = a.sdg;
        if (sdg != null) {
          const n = getSDGNumber(sdg);
          if (n) activitySdgs.add(Number(n));
        }
      });

      const sdgsAddressed = Array.from(activitySdgs).sort((a, b) => a - b);

      const workbook = new ExcelJS.Workbook();
      workbook.creator = "WannaGonna";
      workbook.created = new Date();

      // Tab 1: Impact Summary
      const summarySheet = workbook.addWorksheet("Impact Summary", {views: [{showGridLines: false}]});
      summarySheet.getColumn(1).width = 35;
      summarySheet.getColumn(2).width = 25;
      summarySheet.getColumn(3).width = 25;

      const teal = {argb: "FF009AA2"};
      const orange = {argb: "FFF08602"};
      const gray = {argb: "FF3F3F3F"};
      const lightTeal = {argb: "FFE0F4F5"};
      const borderGray = {argb: "FFCCCCCC"};
      const dark = {argb: "FF1A1A1A"};

      let currentRow = 1;

      // —— Header block ——
      summarySheet.getCell(currentRow, 1).value = orgNameStr;
      summarySheet.getCell(currentRow, 1).font = {bold: true, size: 16, color: {argb: "FF009AA2"}};
      currentRow += 1;
      summarySheet.getCell(currentRow, 1).value = `${t.reportingPeriod}: ${start.toISOString().slice(0, 10)} — ${end.toISOString().slice(0, 10)}`;
      summarySheet.getCell(currentRow, 1).font = {size: 10, color: gray};
      currentRow += 2;

      // Hero block: label row and value row
      const heroLabels = [t.totalActivities, t.uniqueVolunteers, t.totalVolunteerHours];
      heroLabels.forEach((label, i) => {
        const cell = summarySheet.getCell(currentRow, i + 1);
        cell.value = label;
        cell.font = {size: 10, color: gray};
        cell.fill = {type: "pattern", pattern: "solid", fgColor: lightTeal};
        cell.alignment = {horizontal: "center"};
        cell.border = {top: {style: "thin", color: teal}};
      });
      currentRow += 1;
      [activities.length, uniqueVolunteers.size, totalHours].forEach((val, i) => {
        const cell = summarySheet.getCell(currentRow, i + 1);
        cell.value = val;
        cell.font = {bold: true, size: 18, color: teal};
        cell.alignment = {horizontal: "center"};
        cell.border = {bottom: {style: "thin", color: teal}};
      });
      currentRow += 1;

      if (activitiesWithoutDuration > 0) {
        const exclusionNote = `${activitiesWithoutDuration} activit${activitiesWithoutDuration === 1 ? "y" : "ies"} excluded from hour total (no duration recorded).`;
        summarySheet.getCell(currentRow, 1).value = exclusionNote;
        summarySheet.getCell(currentRow, 1).font = {italic: true, size: 9, color: gray};
        summarySheet.getCell(currentRow, 1).alignment = {wrapText: true};
        currentRow += 1;
      }

      currentRow += 1;

      // —— Impact block: A = label, B = breakdown; only rows with value > 0 ——
      const impactTypeOrder = ["reach", "output", "duration", "environmental_output", "organizational_capacity"];
      const impactTypeLabels = {
        reach: t.peopleReached,
        output: t.tangibleOutputs,
        duration: t.serviceHours,
        environmental_output: t.environmentalImpact,
        organizational_capacity: t.organizationalCapacity,
      };

      const byMeasurementType = {};
      for (const [paramId, total] of Object.entries(paramSums)) {
        if (total <= 0) continue;
        const meta = paramMeta[paramId] || {};
        const mt = meta.measurement_type;
        if (!mt) continue;
        if (!byMeasurementType[mt]) byMeasurementType[mt] = [];
        byMeasurementType[mt].push({label: meta.label, unit: meta.unit, total});
      }

      // Add auto-generated org capacity (format: "Label: X h")
      for (const [label, total] of Object.entries(autoGenByCategory)) {
        if (total <= 0) continue;
        if (!byMeasurementType.organizational_capacity) byMeasurementType.organizational_capacity = [];
        byMeasurementType.organizational_capacity.push({
          label,
          unit: "h",
          total: parseFloat(Number(total).toFixed(1)),
        });
      }

      for (const mt of impactTypeOrder) {
        const items = byMeasurementType[mt];
        if (!items || items.length === 0) continue;
        const breakdown = items.map((i) => formatParamValue(i.label, i.total, i.unit)).join(" · ");
        summarySheet.getCell(currentRow, 1).value = impactTypeLabels[mt];
        summarySheet.getCell(currentRow, 1).font = {bold: true, size: 11, color: dark};
        summarySheet.getCell(currentRow, 2).value = breakdown;
        summarySheet.getCell(currentRow, 2).font = {size: 11, color: gray};
        currentRow += 1;
        if (mt === "organizational_capacity" && hasAutoGenParams) {
          summarySheet.getCell(currentRow, 2).value = t.orgCapacityAutoGenNote;
          summarySheet.getCell(currentRow, 2).font = {italic: true, size: 9, color: gray};
          currentRow += 1;
        }
      }

      if (unclassified.length > 0) {
        const breakdown = unclassified.map((u) => formatParamValue(u.label, u.total, u.unit)).join(" · ");
        summarySheet.getCell(currentRow, 1).value = t.unclassifiedParameters;
        summarySheet.getCell(currentRow, 1).font = {bold: true, size: 11, color: dark};
        summarySheet.getCell(currentRow, 2).value = breakdown;
        summarySheet.getCell(currentRow, 2).font = {size: 11, color: gray};
        currentRow += 1;
        summarySheet.getCell(currentRow, 1).value = t.unclassifiedNote;
        summarySheet.getCell(currentRow, 1).font = {italic: true, size: 9, color: gray};
        summarySheet.getCell(currentRow, 1).alignment = {wrapText: true};
        currentRow += 1;
      }

      currentRow += 1;

      // —— SDGs block: label with orange left border; each SDG on own row in col B ——
      summarySheet.getCell(currentRow, 1).value = t.sdgsAddressed;
      summarySheet.getCell(currentRow, 1).font = {bold: true, size: 11};
      summarySheet.getCell(currentRow, 1).border = {left: {style: "thin", color: orange}};
      currentRow += 1;
      if (sdgsAddressed.length > 0) {
        for (const n of sdgsAddressed) {
          summarySheet.getCell(currentRow, 2).value = `${n} - ${t.sdgNames[n] || ""}`;
          summarySheet.getCell(currentRow, 2).font = {size: 11, color: gray};
          currentRow += 1;
        }
      } else {
        summarySheet.getCell(currentRow, 2).value = "-";
        summarySheet.getCell(currentRow, 2).font = {size: 11, color: gray};
        currentRow += 1;
      }
      currentRow += 1;

      // —— Footer: wrap, size 8, gray, italic, top border, row height ——
      summarySheet.getCell(currentRow, 1).value = t.footer;
      summarySheet.getCell(currentRow, 1).font = {italic: true, size: 8, color: gray};
      summarySheet.getCell(currentRow, 1).alignment = {wrapText: true};
      summarySheet.getCell(currentRow, 1).border = {top: {style: "thin", color: borderGray}};
      summarySheet.getRow(currentRow).height = 30;

      summarySheet.tabColor = teal;

      // Tab 2: Activity Log
      const logSheet = workbook.addWorksheet("Activity Log");
      logSheet.views = [{state: "frozen", ySplit: 1}];
      const allParamIds = [...new Set(Object.keys(paramSums))];
      const paramMetaList = allParamIds.map((pid) => {
        const m = paramMeta[pid];
        return {label: m?.label || pid, unit: m?.unit || ""};
      });

      logSheet.getColumn(1).width = 10;
      logSheet.getColumn(2).width = 28;
      logSheet.getColumn(3).width = 12;
      logSheet.getColumn(4).width = 20;
      logSheet.getColumn(5).width = 14;
      logSheet.getColumn(6).width = 14;
      logSheet.getColumn(7).width = 16;
      logSheet.getColumn(8).width = 14;
      logSheet.getColumn(9).width = 18;
      logSheet.getColumn(10).width = 16;
      paramMetaList.forEach((param, i) => {
        logSheet.getColumn(11 + i).width = Math.max(20, (param.label.length || 0) + 5);
      });
      const autoGenColIdx = 11 + paramMetaList.length;
      logSheet.getColumn(autoGenColIdx).width = Math.max(20, 28);

      const logHeaders = [
        t.activityId,
        t.title,
        t.type,
        t.activityCategory,
        t.date,
        t.durationMin,
        t.volunteerCount,
        t.totalHours,
        t.sdgsActivity,
        t.location,
        ...paramMetaList.map((p) => (p.unit || "").trim() ? `${p.label} (${p.unit.trim()})` : p.label),
        t.volunteerHoursContributed,
      ];
      const headerRow = logSheet.addRow(logHeaders);
      headerRow.height = 30;
      headerRow.eachCell((cell, colNumber) => {
        cell.font = {bold: true, size: 10, color: {argb: "FFFFFFFF"}};
        cell.fill = {type: "pattern", pattern: "solid", fgColor: {argb: "FF009AA2"}};
        cell.alignment = {horizontal: "center", vertical: "middle", wrapText: true};
        cell.border = {bottom: {style: "thin", color: {argb: "FF009AA2"}}};
      });
      const volunteerHoursHeaderCell = headerRow.getCell(autoGenColIdx);
      volunteerHoursHeaderCell.font = {italic: true, size: 10, color: {argb: "FF3F3F3F"}};

      const typeMap = {online: t.typeOnline, local: t.typeLocal, event: t.typeEvent};

      for (let idx = 0; idx < activities.length; idx++) {
        const act = activities[idx];
        const durHours = getActivityDurationHours(act);
        const durMin = durHours != null ? Math.round(durHours * 60) : null;
        const volunteerCount = volunteerCountByActivity[act.id] ?? 0;
        const totalHrs = (act.impact_results?.total_hours ?? null) ?? (durHours != null && volunteerCount > 0 ? volunteerCount * durHours : null);
        const sdgVal = act.sdg;
        const sdgNums = sdgVal != null ? [getSDGNumber(sdgVal)] : [];
        const loc = act.type === "online" ? t.locationOnline : (act.city || act.country || act.location || "-");
        const params = act.impact_results?.parameters || {};
        const paramValues = allParamIds.map((pid) => params[pid] ?? "");

        const totalHrsForAct = (act.impact_results?.total_hours ?? 0);
        const autoGen = getAutoGeneratedOrgCapacity(act, volunteerCount, durHours, totalHrsForAct, t.categoryLabels);
        const volunteerHoursContributed = autoGen ? autoGen.value : "";

        const rowData = [
          act.id,
          act.title || "",
          typeMap[act.type] || act.type,
          t.categoryLabels[act.category] || act.category || "",
          (getActivityDateForFilter(act)?.toISOString() ?? "").slice(0, 10),
          durMin ?? "",
          volunteerCount || "",
          totalHrs != null ? parseFloat(Number(totalHrs).toFixed(1)) : "",
          sdgNums.join(", "),
          loc,
          ...paramValues,
          volunteerHoursContributed,
        ];
        const dataRow = logSheet.addRow(rowData);
        if (idx % 2 === 0) {
          dataRow.eachCell({includeEmpty: true}, (cell) => {
            cell.fill = {type: "pattern", pattern: "solid", fgColor: {argb: "FFF5F5F5"}};
          });
        }
        const totalHoursCell = dataRow.getCell(8);
        if (totalHoursCell.value !== "" && totalHoursCell.value != null) {
          totalHoursCell.numFmt = "0.0";
        }
        const volunteerHoursCell = dataRow.getCell(autoGenColIdx);
        if (volunteerHoursCell.value !== "" && volunteerHoursCell.value != null) {
          volunteerHoursCell.numFmt = "0.0";
        }
      }

      logSheet.tabColor = {argb: "FFF08602"};

      // Tab 3: SDG Breakdown
      const sdgSheet = workbook.addWorksheet("SDG Breakdown");
      sdgSheet.views = [{state: "frozen", ySplit: 1}];

      sdgSheet.getColumn(1).width = 14;
      sdgSheet.getColumn(2).width = 28;
      sdgSheet.getColumn(3).width = 16;
      sdgSheet.getColumn(4).width = 16;
      sdgSheet.getColumn(5).width = 22;
      sdgSheet.getColumn(6).width = 20;

      const sdgHeaderRow = sdgSheet.addRow([
        t.sdgNumber,
        t.sdgName,
        t.source,
        t.activityCount,
        t.totalVolunteerHours,
        t.volunteersEngaged,
      ]);
      sdgHeaderRow.eachCell((cell) => {
        cell.font = {bold: true, size: 10, color: {argb: "FFFFFFFF"}};
        cell.fill = {type: "pattern", pattern: "solid", fgColor: {argb: "FF009AA2"}};
        cell.alignment = {horizontal: "center", vertical: "middle", wrapText: true};
        cell.border = {bottom: {style: "thin", color: {argb: "FF009AA2"}}};
      });

      const paramSdgData = {};
      const activitySdgSet = new Set(Object.keys(activitySdgData).map(Number));
      for (const act of activities) {
        const impactParams = act.impact_parameters || [];
        for (const p of impactParams) {
          const def = paramById.get(p.parameter_id || p.id);
          const sdgs = def?.sdg || [];
          for (const sn of sdgs) {
            const n = Number(sn);
            if (activitySdgSet.has(n)) continue;
            if (!paramSdgData[n]) paramSdgData[n] = {activities: new Set()};
            paramSdgData[n].activities.add(act.id);
          }
        }
        // Auto-generated org capacity: inherit activity SDG, only if not already Activity source
        const autoGen = getAutoGeneratedOrgCapacity(
            act,
            volunteerCountByActivity[act.id] ?? 0,
            getActivityDurationHours(act),
            (act.impact_results?.total_hours ?? 0),
            t.categoryLabels,
        );
        if (autoGen) {
          const sdgVals = Array.isArray(autoGen.sdg) ? autoGen.sdg : (autoGen.sdg != null ? [autoGen.sdg] : []);
          for (const sv of sdgVals) {
            const n = Number(getSDGNumber(sv));
            if (!n || activitySdgSet.has(n)) continue;
            if (!paramSdgData[n]) paramSdgData[n] = {activities: new Set()};
            paramSdgData[n].activities.add(act.id);
          }
        }
      }

      let sdgRowIdx = 2;
      const allSdgNums = new Set([...Object.keys(activitySdgData).map(Number), ...Object.keys(paramSdgData).map(Number)]);
      for (const n of [...allSdgNums].sort((a, b) => a - b)) {
        const actData = activitySdgData[n];
        if (actData) {
          const r = sdgSheet.addRow([
            n,
            t.sdgNames[n] || "",
            t.sourceActivity,
            actData.activities.size,
            actData.hours,
            actData.volunteers.size,
          ]);
          if ((sdgRowIdx - 2) % 2 === 0) {
            r.eachCell({includeEmpty: true}, (cell) => {
              cell.fill = {type: "pattern", pattern: "solid", fgColor: {argb: "FFF5F5F5"}};
            });
          }
          sdgRowIdx++;
        }
        const paramData = paramSdgData[n];
        if (paramData) {
          const r = sdgSheet.addRow([n, t.sdgNames[n] || "", t.sourceParameter, paramData.activities.size, "—", "—"]);
          if ((sdgRowIdx - 2) % 2 === 0) {
            r.eachCell({includeEmpty: true}, (cell) => {
              cell.fill = {type: "pattern", pattern: "solid", fgColor: {argb: "FFF5F5F5"}};
            });
          }
          sdgRowIdx++;
        }
      }

      sdgSheet.addRow([]); // blank row before note
      const noteRow = sdgSheet.addRow([]);
      const noteRowIndex = noteRow.number;
      sdgSheet.mergeCells(noteRowIndex, 1, noteRowIndex, 6); // merge BEFORE setting value
      const noteCell = sdgSheet.getCell(noteRowIndex, 1);
      noteCell.value = t.parameterSdgNote;
      noteCell.font = {italic: true, size: 9, color: {argb: "FF3F3F3F"}};
      noteCell.alignment = {wrapText: true, horizontal: "left"};
      noteRow.height = 36;

      sdgSheet.tabColor = {argb: "FF51AC31"};

      const buffer = await workbook.xlsx.writeBuffer();
      const base64 = Buffer.from(buffer).toString("base64");
      const safeName = String(orgNameStr).replace(/[^a-zA-Z0-9\-_\s]/g, "").slice(0, 50).trim() || "NPO";
      const filename = `WannaGonna_Impact_${safeName}_${start.toISOString().slice(0, 10)}_${end.toISOString().slice(0, 10)}.xlsx`;

      return {success: true, base64, filename};
    },
);
